clear;
close all;
clc;

date = '_31_07_23';
%% Define System Parameters
params                  = SimulationParameters; %radius, surface temp, dT/dz, etc.

params.config = 1;
params.S_ratio = 1; %S_ratio = m_S1/m_total
params.find_opt_S_ratio_toggle = 0;
if params.config == 1 || params.config == 2
    params.S_ratio = 1;
end

params.well_radius = 0.4667/2; %m ~18 3/8" inner diameter
params.side_stream_radius = 0.2032/2; %m ~8" inner diameter
params.res_length = 7000;
params.n_streams = 7;

%% Solver toggle    
useMySolver = 1;

%% Collection
A = zeros(30,17);
S = struct;
results = struct;

    filename = strcat('dpo_opt_config1_temperature_drawdown',num2str(date),'.csv');
    %% Calculate
    x0 = 70;
    
    tic;
    [result,x_opt] = AGS_solver(useMySolver,x0,params);

    if result.s_turb_in <= (1.65e3*0.99)
            disp('constraint NOT satisfied')
            con = 0;
    else
        disp('constraint satisfied')
        con = 1;
    end

    toc;                
    A = [result.Power/1e3,...
        ones(1,30)*result.Power_total_sold_avg/1e3,...
        ones(1,30)*result.CapitalCost.C_brownfield/result.Power_total_sold_avg,...
        ones(1,30)*result.CapitalCost.C_greenfield/result.Power_total_sold_avg,...
        ones(1,30)*params.S_ratio,...
        ones(1,30)*params.depth,...
        ones(1,30)*params.res_length,...
        ones(1,30)*params.n_streams,...
        ones(1,30)*x_opt(1),...
        ones(1,30)*result.max_speed,...
        ones(1,30)*result.CapitalCost.C_brownfield,...
        ones(1,30)*result.CapitalCost.C_greenfield,...
        ones(1,30)*result.CapitalCost.CostSurfacePlant,...
        ones(1,30)*result.CapitalCost.CostSubsurface_brownfield,...
        ones(1,30)*result.CapitalCost.CostSubsurface_greenfield,...
        ones(1,30)*con];

T = array2table(A,...
    'VariableNames',{'Power_per_year', ...
    'year',...
    'dH_sold_avg', ...
    'SpCC_dH_Br', ...
    'SpCC_dH_Gr', ...
    'S_ratio',...
    'depth', ...
    'res_length', ...
    'n_streams', ...
    'm_dot', ...
    'max_speed', ...
    'C_Br', ...
    'C_Gr',...
    'C_SurfacePlant',...
    'C_Subsurface_brownfield',...
    'C_Subsurface_greenfield',...
    'con satisfied'});
writetable(T, filename);