function [caption, title] = FigureCaption_Conduction(Ztype, fluid, legendLines, year, WACC, F_OM)
    if (strcmp(Ztype,'Power'))
        if (strcmp(fluid,'CO2'))
            title = {'Power Generated for Conduction CO_{2} Geothermal Systems',' per Injection-Production Well Pair [kW_{e}]'};
        elseif (strcmp(fluid,'Water'))
            title = {'Power Generated for Conduction Water Geothermal Systems',' per Injection-Production Well Pair [kW_{e}]'};
        elseif (strcmp(fluid,'CO2&Water'))
            title = {'Power Generated for Conduction CO_{2} and Water Geothermal Systems',' per Injection-Production Well Pair [kW_{e}]'};
        end
        caption = {'{\bfProperties}'...
            ,'35 °C/km Temp Gradient'...
            ,'15 °C Surface Temp'...
            ,'41 cm Well Diameter'...
            ,'Four Horizontal Laterals'...
            ,'Massflow to Minimize Cost'...
            ,strcat(['Year-' num2str(year) ' Depletion Values'])...
            ,'Adams|Saar, ETH-Zürich (geg.ethz.ch)'};
    elseif (contains(Ztype,'SpCC'))
        if (contains(fluid,'CO2'))
            title = 'Specific Capital Cost for Conduction CO_{2} Geothermal Systems [$/kW_{e}]';
        elseif (strcmp(fluid,'Water'))
            title = 'Specific Capital Cost for Conduction Water Geothermal Systems [$/kW_{e}]';
        elseif (strcmp(fluid,'CO2&Water'))
            title = 'Specific Capital Cost for Conduction CO_{2} and Water Geothermal Systems [$/kW_{e}]';
        end
        caption = {'{\bfProperties}'...
            ,'35 °C/km Temp Gradient'...
            ,'15 °C Surface Temp'...
            ,'41 cm Well Diameter'...
            ,'Four Horizontal Laterals'...
            ,'Massflow to Minimize Cost'...
            ,strcat(['Year-' num2str(year) ' Depletion Values'])...
            ,'Adams|Saar, ETH-Zürich (geg.ethz.ch)'};
    elseif (contains(Ztype,'LCOE'))
        if (contains(fluid,'CO2'))
            title = 'LCOE for Conduction CO_{2} Geothermal Systems [$/(MW_{e}-h)]';
        elseif (strcmp(fluid,'Water'))
            title = 'LCOE for Conduction Water Geothermal Systems [$/(MW_{e}-h)]';
        elseif (strcmp(fluid,'CO2&Water'))
            title = 'LCOE for Conduction CO_{2} and Water Geothermal Systems [$/(MW_{e}-h)]';
        end
        caption = {'{\bfProperties}'...
            ,'35 °C/km Temp Gradient'...
            ,'15 °C Surface Temp'...
            ,'41 cm Well Diameter'...
            ,'Four Horizontal Laterals'...
            ,'Massflow to Minimize Cost'...
            ,strcat([ num2str(WACC) '% WACC, 25-year Lifetime, ' num2str(F_OM) '% O&M'])...
            ,strcat(['Year-' num2str(year) ' Depletion Values'])...
            ,'Adams|Saar, ETH-Zürich (geg.ethz.ch)'};
    end
    
    if (~isempty(legendLines))
        caption = vertcat(caption{1:4},legendLines(:),caption{5:end});
    end
    
end

